# Generated by Django 4.2.15 on 2024-08-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('regular_hour_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('overtime_hour_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('fortnight_start', models.DateField(blank=True, null=True)),
                ('fortnight_end', models.DateField(blank=True, null=True)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('housing_deduction_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('transportation_deduction_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('miscellaneous_deduction_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
